name: azure-function_nitro-js
on:
  push:
    branches:
        - main
  pull_request:
    branches:
        - main
jobs:
  deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [ 20 ]
    steps:
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Checkout
        uses: actions/checkout@master

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build
        env:
          NITRO_PRESET: azure_functions

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: basketballServer
          package: .output/deploy.zip
          publish-profile: ${{ secrets.AZURE_FUNCTION_APP_PUBLISH_PROFILE }}
      
